export enum ShipmentStatus {
  PENDING = 'PENDING',
  RECEIVED_ORIGIN = 'RECEIVED_ORIGIN',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED_HUB = 'ARRIVED_HUB',
  IN_WAREHOUSE = 'IN_WAREHOUSE',
  CUSTOMS_CLEARANCE = 'CUSTOMS_CLEARANCE',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}
